#!/bin/sh

exec >> history.log
exec 2>&1

endlog() {
    echo "$1"
    printf "______________\n\n\n"
}

[ ! -L data_backup_dest ] &&
    echo "ERROR: data_backup_dest link doesn't exists" &&
    endlog "backup ABORTING" &&
    exit 1

backup_dest=$(readlink data_backup_dest)

[ ! -d "$backup_dest" ] &&
    echo "ERROR: the dir data_backup_dest points to doesn't exists" &&
    endlog "backup ABORTING" &&
    exit 1

[ ! -d tracking ] &&
    echo "ERROR: the tracking dir doesn't exists" &&
    endlog "backup ABORTING" &&
    exit 1

date
echo "saving to $backup_dest"
echo "backup STARTING"

rsync -aczLvh --del tracking/ data_backup_dest

endlog "backup FINISHED"
