#!/bin/sh

endlog() {
    echo "$1"
    echo "______________"
}

Backup() {
    echo
    echo
    date
    echo "saving to $backup_dest"
    echo "backup STARTING"

    rsync -aczLvh --del --exclude=.gitignore tracking/ data_backup_dest

    endlog "backup FINISHED"
}

[ ! -L data_backup_dest ] &&
    echo "ERROR: data_backup_dest link doesn't exists" &&
    endlog "backup ABORTING" &&
    exit 1

[ ! -d tracking ] &&
    echo "ERROR: the tracking dir doesn't exists" &&
    endlog "backup ABORTING" &&
    exit 1

backup_dest=$(readlink data_backup_dest)

[ ! -d "$backup_dest" ] &&
    echo "ERROR: the dir data_backup_dest points to doesn't exists" &&
    endlog "backup ABORTING" &&
    exit 1

Backup 2>&1 | tee -a "history.log"
