#!/bin/sh

usage() {
    echo "usage: $0 path"
    echo
    echo "path"
    echo "    the path to an existing file or directory to track for backups"

}

fatal() {
    echo "$*" >&2
    exit 1
}

[ ! "$1" ] && { usage >&2; exit 1; }
[ "$1" = "-h" ] && { usage; exit 0; }
[ "$1" = "--help" ] && { usage; exit 0; }

data_path=$1
data_name=$(echo "$data_path" | xargs basename)

[ ! -e "$data_path" ] &&
    fatal "ERROR: that path does not exist"

[ "${data_path%%/*}" ] &&
    fatal "ERROR: must give the absolute path to the data"

[ -L "tracking/$data_name" ] &&
    fatal "ERROR: there is already file or directory with that name in tracking"

ln -sFhi "$data_path" "tracking/$data_name" &&
    echo "SUCCESS: that data is now being tracked" >&2
